whill_joy2:
  ros__parameters:
    axis_liner: 1
    axis_angular: 0
    buttons_deadman: 5  
    scale_angular: 0.8
    scale_linear: 0.567
    buttons_stop: 0
    buttons_rotation_R: 5
    buttons_rotation_L: 2
    buttons_straight: 2
    cmd_only: true
    frequency: 10