witmotion_ros_node:
  ros__parameters:
    port: /dev/ttyUSB1
    baud_rate: 115200  # baud
    polling_interval: 100  # ms
    timeout_ms: 150  # ms
    restart_service_name: /restart_imu
    imu_publisher:
      topic_name: witmotion/imu/data_raw
      frame_id: imu_wit
      use_native_orientation: false  # if true, using magnetometer instead of imu data
      measurements:
        acceleration:
          enabled: true
          covariance: [0.0364, 0.0, 0.0, 0.0, 0.0048, 0.0, 0.0, 0.0, 0.0796]
        angular_velocity:
          enabled: true
          covariance: [0.0663, 0.0, 0.0, 0.0, 0.1453, 0.0, 0.0, 0.0, 0.0378]
        orientation:
          enabled: true
          covariance: [0.0479, 0.0, 0.0, 0.0, 0.0207, 0.0, 0.0, 0.0, 0.0041]
    temperature_publisher:
      enabled: true
      topic_name: /temperature
      frame_id: base_link
      from_message: magnetometer  # acceleration, angular_vel, orientation, magnetometer
      variance: 0.01829
      coefficient: 1.0  # Linear calibration parameters: coefficient
      addition: 0.0  # and addendum
    magnetometer_publisher:
      enabled: true
      topic_name: /magnetometer
      frame_id: compass
      coefficient: 0.00000001  # Linear calibration parameters: coefficient
      addition: 0.0  # and addendum
      covariance:
        [0.000000187123, 0.0, 0.0, 0.0, 0.000000105373, 0.0, 0.0, 0.0, 0.000000165816]
    barometer_publisher:
      enabled: false
      topic_name: /barometer
      frame_id: base_link
      variance: 0.001
      coefficient: 1.0  # Linear calibration parameters: coefficient
      addition: 0.0  # and addendum
    altimeter_publisher:
      enabled: false
      topic_name: /altitude
      coefficient: 1.0  # Linear calibration parameters: coefficient
      addition: 0.0  # and addendum
    orientation_publisher:
      enabled: true
      topic_name: /orientation
    gps_publisher:
      enabled: false
      navsat_fix_frame_id: world
      navsat_fix_topic_name: /gps
      navsat_altitude_topic_name: /gps_altitude
      navsat_satellites_topic_name: /gps_satellites
      navsat_variance_topic_name: /gps_variance
      ground_speed_topic_name: /gps_ground_speed
    rtc_publisher:
      enabled: false
      topic_name: /witmotion_clock

wit_imu_filter_node:
  ros__parameters:
    constant_dt: 0.0
    declination: 0.0
    fixed_frame: base_link
    gain: 0.1
    mag_bias_x: 0.0
    mag_bias_y: 0.0
    mag_bias_z: 0.0
    orientation_stddev: 0.0
    publish_debug_topics: false
    publish_tf: false
    remove_gravity_vector: false
    reverse_tf: false
    stateless: false
    use_mag: true
    world_frame: enu
    yaw_offset: 0.0
    zeta: 0.0