ntrip_client_node:
  ros__parameters:
    check_gga: true
    debug: false
    host_url: ntrip.ales-corp.co.jp
    mountpoint: 32M4NHS
    password: bh2ket
    port: 2101
    username: 8wna5x52

zed_f9p_node:
  ros__parameters:
    port: /dev/ttyACM1
    baud: 230400
    use_rtk: true
    rate: 20
    debug: false
    frame_id: ublox