ublox_gnss_launch:
  use_rtk: 'true'
  port: '/dev/ttyACM1'
  debug: 'false'
  check_gga: 'true'
  mountpoint: '32M4NHS'
  frame_id: 'ublox'
  serial_baud: '230400'  
  rate: '20.0'  
  ntrip_usrname: '8wna5x52'  
  ntrip_passwd: 'bh2ket'  
  ntrip_host: 'ntrip.ales-corp.co.jp'  
  ntrip_port: '2101'  